Repository mia-ajuda/Frontend, pull requests merged in 2021-07, with the labels that each got.

#159 Add logic to doesn't show offer in map while offer is turned off
  app/src/Navigation/MainNavigation/ActivitiesNavigator/index.js
  app/src/components/CreateHelpButtons/index.js
  app/src/docs/FAQ/faqOptions.js
  app/src/docs/filterMarkers.js
  app/src/pages/Main/index.js
  app/src/utils/isOffersTurnedOff.js
Labels: bug

#160 Atualização do Expo SDK para versão 42
  app/App.js
  app/package-lock.json
  app/package.json
  app/src/Navigation/MainNavigation/ActivitiesNavigator/index.js
  app/src/Navigation/MainNavigation/MapStackNavigator/index.js
  app/src/Navigation/MainNavigation/NotificationNavigator/index.js
  app/src/pages/AuthPages/Photo/index.js
  app/src/pages/HelpPages/CreateCampaign/index.js
  app/src/pages/HelpPages/CreateHelpOffer/index.js
  app/src/pages/HelpPages/CreateHelpRequest/index.js
  app/src/pages/Profile/UserProfile/index.js
  app/src/services/Entity.js
  app/src/services/User.js
  app/src/store/contexts/userContext.js
  app/yarn.lock
Labels: enhancement

#161 Solve - Updating Contributing Guide
  CONTRIBUTING.md
  app/package-lock.json
  app/package.json
Labels: documentation
