Repository mia-ajuda/Frontend, pull requests merged in 2023-05, with the labels that each got.

#231 HOTFIX - Loading múltiplo em algumas telas
  app/src/components/molecules/CustomHeader/index.jsx
  app/src/components/molecules/UserListItem/index.jsx
  app/src/components/profileList/index.jsx
  app/src/index.js
  app/src/pages/EditProfile/index.jsx
  app/src/pages/FindUsersPages/index.jsx
  app/src/pages/UserList/index.jsx
  app/src/pages/UserProfile/index.jsx
  app/src/store/contexts/updaterContext.jsx
Labels: bug

#229 US03 - Eu, como usuário ajudante, desejo ter um reconhecimento quando criar uma oferta ou oferecer ajuda a um pedido no aplicativo, para que eu possa me sentir bem sempre que entrar no aplicativo
  app/src/components/atoms/CircleBadge/index.jsx
  app/src/components/modals/BadgeEarnModal/index.jsx
  app/src/components/modals/BaseModal/index.jsx
  app/src/components/molecules/BadgeCard/index.jsx
  app/src/pages/AuthPages/Location/index.jsx
  app/src/pages/HelpPages/MapHelpDescription/index.jsx
  app/src/store/contexts/badgeContext.jsx
Labels: enhancement

#233 Refatora a tela de "Meus Pedidos"
  app/src/Navigation/MainNavigation/GivenHelps/index.jsx
  app/src/Navigation/MainNavigation/MainNavigationStyles/MainStackHeaderStyle.jsx
  app/src/Navigation/MainNavigation/MyRequestHelpDescription/index.jsx
  app/src/Navigation/MainNavigation/Routes/ActivitiesRoutes/index.jsx
  app/src/Navigation/MainNavigation/Routes/ProfileRoutes/index.jsx
  app/src/Navigation/MainNavigation/Routes/SocialNetworkRoutes/index.jsx
  app/src/Navigation/MainNavigation/screenOptions.js
  app/src/Navigation/tabTopBarOptions.js
  app/src/components/HelpersInfo/index.jsx
  app/src/components/HelpersInfo/styles.js
  app/src/components/InterestedList/index.jsx
  app/src/components/InterestedList/styles.js
  app/src/components/NotificationCard/index.js
  app/src/components/UserItem/index.jsx
  app/src/components/atoms/DefaultButton/index.jsx
  app/src/components/atoms/InformativeField/index.jsx
  app/src/components/atoms/UserProfileCard/index.jsx
  app/src/components/modals/chosenHelpersInfo/index.js
  app/src/components/modals/expansiveModal/index.js
  app/src/components/molecules/Badge/index.jsx
  app/src/components/molecules/CategoriesList/index.jsx
  app/src/components/molecules/CustomHeader/index.jsx
  app/src/components/templates/BordedScreenLayout/index.jsx
  app/src/components/templates/HelpScreenLayout/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/styles.js
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/FinishHelpButton/index.jsx
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.js
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/styles.js
  app/src/pages/ActivitiesPages/MyRequestedHelp/index.jsx
  app/src/pages/ActivitiesPages/SelectedHelpOnMap/index.jsx
  app/src/pages/FindUsersPages/SocialNetworkProfile/index.jsx
  app/src/pages/HelpPages/MapHelpDescription/index.jsx
  app/src/pages/UserProfile/index.jsx
  app/src/services/User.js
  app/src/store/contexts/helpContext.js
  app/src/store/contexts/userContext.js
  app/src/utils/navigateToDescription.js
  app/tailwind.config.js
Labels: refactoring, frontend

#237 Atualização do eslint
  app/package.json
  app/src/Navigation/MainNavigation/Routes/MapRoutes/index.jsx
  app/src/Navigation/MainNavigation/Routes/MoreInfoRoutes/index.jsx
  app/src/components/atoms/Divider/index.jsx
  app/src/components/atoms/Input/index.jsx
  app/src/components/modals/BadgeEarnModal/index.jsx
  app/src/components/molecules/CustomDrawerItem/index.jsx
  app/src/components/molecules/UserListItem/index.jsx
  app/src/components/organisms/ActivityCard/index.jsx
  app/src/components/organisms/HorizontalList/index.jsx
  app/src/pages/AuthPages/ForgotPassword/index.jsx
  app/src/pages/UserProfile/index.jsx
  app/src/store/contexts/loadingContext.jsx
Labels: bug, enhancement
