Repository mia-ajuda/Frontend, pull requests merged in 2023-04, with the labels that each got.

#217 Refatoração da tela de detalhes das Minhas Ofertas
  app/assets/styles/helpDescription.js
  app/babel.config.js
  app/package.json
  app/src/Navigation/MainNavigation/Routes/ActivitiesRoutes/index.jsx
  app/src/components/CustomMap/index.js
  app/src/components/InterestedList/UserCard.js
  app/src/components/UserItem/index.jsx
  app/src/components/atoms/CircleIconButton/index.jsx
  app/src/components/atoms/DefaultButton/index.jsx
  app/src/components/atoms/RoundedFullButton/index.jsx
  app/src/components/modals/confirmationModal/styles.js
  app/src/components/modals/expansiveModal/index.js
  app/src/components/molecules/DefaultButtonWithBagdes/index.jsx
  app/src/components/molecules/FloatingIconButton/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/styles.js
  app/src/pages/ActivitiesPages/SelectedHelpOnMap/index.jsx
  app/src/pages/Main/HelpOfferMarker/index.js
  app/src/pages/Main/index.js
  app/tailwind.config.js
  app/yarn.lock
Labels: refactoring, frontend

#223 222 - Eu, como usuário, desejo poder seguir outras pessoas no aplicativo, para que eu possa acessar seus perfis de maneira rápida
  app/assets/images/noImage.png
  app/assets/images/notFoundImage.svg
  app/src/Navigation/MainNavigation/index.jsx
  app/src/components/UserItem/index.jsx
  app/src/components/atoms/IconButton/index.jsx
  app/src/components/atoms/RoundedFullButton/index.jsx
  app/src/components/atoms/SearchBar/index.jsx
  app/src/components/atoms/SearchBar/styles.js
  app/src/components/molecules/UserListItem/index.jsx
  app/src/components/molecules/UserListItem/styles.js
  app/src/components/organisms/NotFound/index.jsx
  app/src/components/organisms/NotFound/styles.js
  app/src/components/profileList/index.js
  app/src/components/profileList/index.jsx
  app/src/components/profileList/styles.js
  app/src/index.js
  app/src/pages/FindUsersPages/index.jsx
  app/src/pages/FindUsersPages/styles.js
  app/src/services/socialNetworkProfile.js
  app/src/store/contexts/loadingContext.jsx
  app/src/store/contexts/socialNetworkProfileContext.jsx
  app/src/store/contexts/updaterContext.jsx
Labels: enhancement, refactoring

#224 US09 -Eu, como usuário, desejo poder visualizar perfis de outras pessoas no aplicativo Mia Ajuda para que possa compreender o que fizeram no aplicativo
  app/src/Navigation/MainNavigation/Routes/SocialNetworkRoutes/index.jsx
  app/src/components/HistoricCard/styles.js
  app/src/components/UserItem/index.jsx
  app/src/components/atoms/DefaultButton/index.jsx
  app/src/components/atoms/RoundedFullButton/index.jsx
  app/src/components/atoms/TextSwitchButton/index.jsx
  app/src/components/follow_followingText/index.js
  app/src/components/follow_followingText/styles.js
  app/src/components/molecules/Badge/index.jsx
  app/src/components/molecules/DescriptionBox/index.jsx
  app/src/components/molecules/FollowCount/index.jsx
  app/src/components/molecules/TextSwitch/index.jsx
  app/src/components/molecules/UserListItem/index.jsx
  app/src/components/organisms/ActivitiesList/index.jsx
  app/src/components/organisms/ActivityCard/index.jsx
  app/src/components/organisms/NotFound/index.jsx
  app/src/components/organisms/NotFound/styles.js
  app/src/components/profileList/index.jsx
  app/src/index.js
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.jsx
  app/src/pages/FindUsersPages/Followers_Following/index.jsx
  app/src/pages/FindUsersPages/index.jsx
  app/src/pages/Main/CampaignMarker/index.js
  app/src/pages/Profile/UserProfile/index.jsx
  app/src/pages/UserList/index.jsx
  app/src/pages/UserProfile/index.jsx
  app/src/services/Campaign.js
  app/src/services/socialNetworkProfile.js
  app/src/store/contexts/activitiesContext.jsx
  app/src/store/contexts/socialNetworkProfileContext.jsx
  app/src/utils/navigateToDescription.js
  app/tailwind.config.js
Labels: enhancement

#226 Altera o header do aplicativo para seguir a nova versão prototipada
  app/src/components/molecules/CustomHeader/index.jsx
  app/src/components/molecules/CustomHeader/styles.js
  app/src/utils/getScreenTitle.js
Labels: refactoring, frontend

#228 Adiciona botões auxiliares no header
  app/src/Navigation/MainNavigation/MainNavigationStyles/MainStackHeaderStyle.jsx
  app/src/Navigation/MainNavigation/Routes/ProfileRoutes/index.jsx
  app/src/Navigation/MainNavigation/Routes/SocialNetworkRoutes/index.jsx
  app/src/components/molecules/CustomHeader/index.jsx
  app/src/pages/UserProfile/index.jsx
Labels: refactoring, frontend
