Repository mia-ajuda/Frontend, pull requests merged in 2023-06, with the labels that each got.

#236 227 new activity modal
  app/colors.js
  app/src/components/HelpList/index.js
  app/src/components/atoms/CircleIconButton/index.jsx
  app/src/components/atoms/DefaultButton/index.jsx
  app/src/components/modals/ActivityBottomSheet/EntityActivity.jsx
  app/src/components/modals/ActivityBottomSheet/UserActivity/index.jsx
  app/src/components/modals/ActivityBottomSheet/index.jsx
  app/src/components/modals/BaseBottomSheet/index.jsx
  app/src/components/modals/expansiveModal/index.js
  app/src/components/modals/expansiveModal/index.jsx
  app/src/components/molecules/ActivityMarker/index.jsx
  app/src/components/molecules/CategoriesList/index.jsx
  app/src/components/organisms/ActivitiesList/index.jsx
  app/src/components/organisms/ActivityCard/index.jsx
  app/src/components/templates/HelpScreenLayout/index.jsx
  app/src/index.js
  app/src/pages/AuthPages/Address/index.jsx
  app/src/pages/AuthPages/Photo/index.js
  app/src/pages/HelpPages/MapHelpDescription/index.jsx
  app/src/pages/Main/index.jsx
  app/src/pages/UserProfile/index.jsx
  app/src/store/contexts/activitiesContext.jsx
  app/src/store/contexts/activityBottomSheetContext.jsx
  app/src/utils/navigateToDescription.js
  app/src/utils/openMaps.js
  app/src/utils/openWhatsapp.js
  app/src/utils/shortenName.js
  app/tailwind.config.js
Labels: enhancement

#239 Correção no fluxo de navegação de criação de pedido/oferta pela primeira vez
  app/src/pages/AuthPages/Photo/index.js
Labels: bug

#240 Fluxo de Feedback
  app/colors.js
  app/package.json
  app/src/Navigation/MainNavigation/Routes/FeedbackRoutes/index.jsx
  app/src/Navigation/MainNavigation/Routes/index.jsx
  app/src/Navigation/MainNavigation/index.jsx
  app/src/components/atoms/Input/index.jsx
  app/src/components/modals/BaseModal/index.jsx
  app/src/components/molecules/Dialog/index.jsx
  app/src/components/organisms/CustomDrawerList/index.jsx
  app/src/index.js
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/FeedbackModal/index.jsx
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
  app/src/pages/Feedback/FeedbackItem/index.jsx
  app/src/pages/Feedback/index.jsx
  app/src/services/Feedback.js
  app/src/store/contexts/feedbackContext.jsx
  app/src/store/contexts/helpContext.js
  app/src/templates/ScreenTemplate/index.jsx
  app/src/utils/getScreenTitle.js
  app/yarn.lock
Labels: enhancement, frontend

#241 Padronizando modais de confirmação do aplicativo
  app/src/components/modals/ActivityBottomSheet/UserActivity/index.jsx
  app/src/components/modals/confirmationModal/index.jsx
  app/src/components/modals/confirmationModal/styles.js
  app/src/components/modals/expansiveModal/index.jsx
  app/src/components/molecules/Dialog/index.jsx
  app/src/pages/ActivitiesPages/MyCampaigns/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.jsx
  app/src/pages/ActivitiesPages/MyOfferedHelp/index.jsx
  app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
  app/src/pages/ActivitiesPages/MyRequestedHelp/index.jsx
  app/src/pages/AuthPages/Location/index.jsx
  app/src/pages/HelpPages/CampaignDescription/index.jsx
  app/src/pages/HelpPages/MapHelpDescription/index.jsx
Labels: refactoring

#243 235 - Envio da localização do usuário para o backend
  app/src/store/contexts/userContext.js
  app/src/utils/navigateToDescription.js
Labels: enhancement

#247 Mescla as categorias individuais em lista de atividades
  app/src/Navigation/index.jsx
  app/src/index.js
  app/src/pages/Main/index.jsx
  app/src/services/Activity.js
  app/src/services/Help.js
  app/src/store/contexts/activitiesContext.jsx
  app/src/store/contexts/campaignContext.js
  app/src/store/contexts/helpContext.js
  app/src/store/contexts/helpOfferContext.js
Labels: frontend
